name: eglise_de_ville
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 5.0.0+10007

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter # Add this line

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_zoom_drawer: ^3.0.1
  # mysql1: ^0.19.2
  flutter_staggered_grid_view: ^0.6.1
  table_calendar: ^3.0.5
  # intl:
  lottie:
  font_awesome_flutter:
  flutter_quill: ^4.1.3
  file_picker: ^4.5.1
  # html_editor_enhanced: ^2.4.0+1
  # html_editor: ^1.0.1
  carousel_slider: ^4.1.1

  # localization:
  time_range_picker: any
  http:
  url_launcher: ^6.1.0
  flutter_local_notifications: ^9.5.2
  # flutter_native_timezone:
  overlay_support:
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0
  photo_view: ^0.13.0
  background_fetch: ^1.1.0
  sqflite: ^2.0.2+1
  # flutter_link_previewer:
  # simple_url_preview: ^3.0.1
  # download_assets: ^3.0.0
  # path_provider: ^2.0.11
  archive: ^3.3.0
  flutter_cache_manager: ^3.3.0
  animations:
  badges: ^2.0.3
  dots_indicator: ^2.1.0
  kkiapay_flutter_sdk: ^1.1.0
  # flutter_lyric: ^2.0.4+6
  # audioplayers:
  google_nav_bar: ^5.0.6
  firebase_core:
  in_app_update:
  google_sign_in:
  flutter_timer_countdown:

  # subtitle: ^0.1.0-beta.3
  # google_one_tap_sign_in:
  # share:
  # auto_size_text:
  # bubble_bottom_bar: ^2.0.0
  # animated_bottom_navigation_bar: ^0.3.2
  # flutter_video_compress: ^0.3.7+8
  # simple_url_preview_v2:
  lecle_flutter_link_preview:
  flutter_sound: ^9.2.13
  audio_waveforms: ^1.0.4
  flutter_audio_waveforms:
  audioplayers:
  cupertino_progress_bar: ^0.2.0

  # dio:

  # multipart_request: ^0.3.1
  # audio_waveforms_fix: ^0.0.2
  # neplox_linkpreviewer:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo_round.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lotties/
    - assets/image/
    - assets/bible_sql.zip

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Circular
      fonts:
        - asset: fonts/CircularStd-Medium.ttf
        - asset: fonts/CircularAir-Light.ttf
          weight: 100
        - asset: fonts/CircularStd-Bold.ttf
          weight: 500
    - family: Awake
      fonts:
        - asset: fonts/Awake.ttf
    # - family: NotoEmoji
    #   fonts:
    #     - asset: fonts/NotoEmoji-Light.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 300
        - asset: fonts/Montserrat-Light.ttf
          weight: 500
        - asset: fonts/Montserrat-Medium.ttf
          weight: 700
        - asset: fonts/Montserrat-Regular.ttf
          weight: 600
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Light.ttf
          weight: 200
        - asset: fonts/SourceSansPro-LightItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/SourceSansPro-Regular.ttf
          weight: 500
        - asset: fonts/SourceSansPro-Italic.ttf
          style: italic
          weight: 500
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 700
        - asset: fonts/SourceSansPro-SemiBoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 800
        - asset: fonts/SourceSansPro-BoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/SourceSansPro-Black.ttf
          weight: 900
        - asset: fonts/SourceSansPro-BlackItalic.ttf
          weight: 900
          style: italic

  # fonts: fonts\NotoEmoji-Light.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
